using System;



namespace Console_Pokedex
{

    class WelcomeScreen
    {
        public void welcome() {
            Console.ForegroundColor = ConsoleColor.Blue;

            Console.SetCursorPosition(100, 1);
            Console.Write(",,///");

            Console.SetCursorPosition(98, 2);
            Console.Write(",,//////");

            Console.SetCursorPosition(97, 3);
            Console.Write("*///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///*");

            Console.SetCursorPosition(95, 4);
            Console.Write("*////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(76, 5);
            Console.Write("/  ,/            **///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####(");
            Console.ForegroundColor = ConsoleColor.Blue;

            Console.Write("/////");
            Console.SetCursorPosition(35, 6);
            Console.Write("*////*                             ///////,,/////       **///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////                 **//////////");

            Console.SetCursorPosition(27, 7);
            Console.Write("/////////////////////               ,/////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////    ,,,,/////////*      ,,*/////////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///           *//");

            Console.SetCursorPosition(22, 8);
            Console.Write("*///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("//////((///////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////,         ,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("///(###//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#///");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////   ,////////////////  ,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("///////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///         ,,*///////////");

            Console.SetCursorPosition(19, 9);
            Console.Write("//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("//##################///");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////        ,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(####(//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("//(####(////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//         ,,*//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("//////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////// ,////");

            Console.SetCursorPosition(16, 10);
            Console.Write(",////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("/##########################//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///       ***/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("########(//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##############///");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//*        ***////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///,///////////");

            Console.SetCursorPosition(15, 11);
            Console.Write(",,,////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###########################//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///      ***/,,//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(####(/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##########");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(####");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("########//#######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///        **,,,//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(//////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");

            Console.SetCursorPosition(16, 12);
            Console.Write(",,,*///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###############");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///         ,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###############");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//   //");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("########//#######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/// //////////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");

            Console.SetCursorPosition(17, 13);
            Console.Write(",,,*///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#############(/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///  /////////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#############");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("// //");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(###");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////,//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#################//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("//(((////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######(/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(18, 14);
            Console.Write("****///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#########/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//* ///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("/////////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(##########");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////  ///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###################");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(##");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("/(#####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(19, 15);
            Console.Write("****///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#########/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("// ///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(###");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("/####(//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######///");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####(####(///####(//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###############/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####(/##//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(21, 16);
            Console.Write("******///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(########/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(###");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#########(////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####################");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####(##/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(25, 17);
            Console.Write("***///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(########/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("((");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##############//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###############");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#(/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###//#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(26, 18);
            Console.Write(",,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("############(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######(//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#((");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/////######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##########/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//*");

            Console.SetCursorPosition(27, 19);
            Console.Write(",,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("########(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////*,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######//////#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######////");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//////////,,,,,//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###############");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##(/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#########/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(28, 20);
            Console.Write(",,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######)/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("################/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//*,,*//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######(//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///,,    ,,///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//,///////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("############(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("###/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("########(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(28, 21);
            Console.Write(",,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//*,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##############/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//* ,,,,,*//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///      ,,,,,/////////,,//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("##//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(######");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("########/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(29, 22);
            Console.Write(",,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(##########");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//*     ,,,,,*//////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///            ,,,,,,,,,,,/,,//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(###///");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("/////////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####(/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(30, 23);
            Console.Write(",,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///,,,,//////////////,,//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("((");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("//////*         ,,,,,,//////                       ,,,/////////////,  ,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(31, 24);
            Console.Write(",,,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####(/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///  ,,,,,*//////,, ,,,/////////,              ,,,,,,//                       ,,,,,,,,////////   ,,,///////////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("######/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(32, 25);
            Console.Write(",,,*///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####//");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///     ,,,,,      ,,,,,,");
            Console.SetCursorPosition(96, 25);
            Console.Write(",,,");
            Console.SetCursorPosition(131, 25);
            Console.Write(",,,,,,,     ,,,,,,,,,,,//");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("#####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(33, 26);
            Console.Write(",,,///");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(####/");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("////");
            Console.SetCursorPosition(151, 26);
            Console.Write(",,,////");
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.Write("(#(");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("///");

            Console.SetCursorPosition(34, 27);
            Console.Write(",,,//////////*,");
            Console.SetCursorPosition(151, 27);
            Console.Write(",,,,,////////");

            Console.SetCursorPosition(35, 28);
            Console.Write(",,,///,,,");
            Console.SetCursorPosition(155, 27);
            Console.Write(",,,,,,,/");

        }
    }
}
